[package]
name = "db"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
domain = { path = "../domain" }
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
